module.exports = {
  "multipass": true,
  "plugins": [
    { "name": "removeDoctype" },
    { "name": "removeXMLProcInst" },
    { "name": "removeComments" },
    { "name": "removeMetadata" },
    { "name": "removeTitle" },
    { "name": "removeDesc" },
    { "name": "removeUselessDefs" },
    { "name": "removeEditorsNSData" },
    { "name": "removeEmptyAttrs" },
    { "name": "removeHiddenElems" },
    { "name": "removeEmptyText" },
    { "name": "removeEmptyContainers" },
    { "name": "cleanupEnableBackground" },
    { "name": "convertStyleToAttrs" },
    { "name": "convertColors" },
    { "name": "convertPathData" },
    { "name": "convertTransform" },
    { "name": "removeUnknownsAndDefaults" },
    { "name": "removeNonInheritableGroupAttrs" },
    { "name": "removeUselessStrokeAndFill" },
    { "name": "removeUnusedNS" },
    { "name": "cleanupNumericValues" },
    { "name": "moveElemsAttrsToGroup" },
    { "name": "moveGroupAttrsToElems" },
    { "name": "collapseGroups" },
    { "name": "mergePaths" },
    { "name": "convertShapeToPath" },
    { "name": "sortAttrs" },
    { "name": "removeDimensions" }
  ]
};
